### ISSUE TITLE
Error in basic-server.js

### ISSUE THREAD

**Issue by nokai** [jhead/node-mcpe#1]
$ babel-node examples/basic-server.js
Listening on 0.0.0.0:19132

/Users/Downloads/node-mcpe-master 3/lib/net/DataTypes.js:253
      var value = buffer.readUIntBE(2, 6);
                         ^
TypeError: Object

**Comment by jhead** [comment]
Hello!

Could you tell me what version of Node.js/io.js you're using? I'm using io.js v2.4.0 and not experiencing the same error.

**Comment by nokai** [comment]
update and works, Thanks
