### ISSUE TITLE
consider using pocket-minecraft-protocol

### ISSUE THREAD

**Issue by ghost** [jhead/node-mcpe#2]
Hi!

Not sure if this project was just  for fun or not, but I've created a library for interacting with raknet here: https://github.com/mhsjlw/node-raknet and a library for interacting with the `0.14.2` (at the time of speaking) mcpe protocol: https://github.com/mhsjlw/pocket-minecraft-protocol

I think it would be useful for you, if not, sorry for bothering, you may close this issue.

**Comment by jhead** [comment]
Hey!

This project is purely for fun and to learn the inner workings of PE and the PE protocol. There weren't any libraries offering this kind of functionality when I started, but I've been too busy lately to keep working on it. I'll definitely check yours out :)

**Comment by ghost** [comment]
Awesome! It's also worth noting: https://github.com/numerous-alpaca/numerous-alpaca the start of a Minecraft: PE 0.14.2 server, it has spawning in, chatting, a world, movement, creative and survival mode and a (very) basic plugin API. If you're looking for a fun project to work on, definetly check that out
